import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import { StandingTable } from "./StandingTable";
import { StandingTableRow } from "./types";

const meta = {
  component: StandingTable,
  parameters: {
    layout: "fullscreen",
  },
} satisfies Meta<typeof StandingTable>;

export default meta;
type Story = StoryObj<typeof meta>;

const rows: StandingTableRow[] = [
  {
    position: 1,
    team: "Manchester City",
    played: 38,
    won: 28,
    drawn: 5,
    lost: 5,
    goalsFor: 96,
    goalsAgainst: 35,
    points: 89,
    form: ["W", "W", "W", "W", "W"],
  },
  {
    position: 2,
    team: "Arsenal",
    played: 38,
    won: 26,
    drawn: 6,
    lost: 6,
    goalsFor: 88,
    goalsAgainst: 43,
    points: 84,
    form: ["W", "W", "W", "D", "W"],
  },
  {
    position: 3,
    team: "Liverpool",
    played: 38,
    won: 25,
    drawn: 8,
    lost: 5,
    goalsFor: 86,
    goalsAgainst: 41,
    points: 83,
    form: ["W", "D", "W", "W", "L"],
  },
  {
    position: 4,
    team: "Aston Villa",
    played: 38,
    won: 20,
    drawn: 8,
    lost: 10,
    goalsFor: 76,
    goalsAgainst: 61,
    points: 68,
    form: ["W", "L", "W", "D", "W"],
  },
  {
    position: 5,
    team: "Tottenham",
    played: 38,
    won: 20,
    drawn: 6,
    lost: 12,
    goalsFor: 74,
    goalsAgainst: 61,
    points: 66,
    form: ["L", "W", "W", "L", "W"],
  },
  {
    position: 6,
    team: "Chelsea",
    played: 38,
    won: 18,
    drawn: 9,
    lost: 11,
    goalsFor: 77,
    goalsAgainst: 63,
    points: 63,
    form: ["W", "D", "D", "W", "L"],
  },
  {
    position: 7,
    team: "Newcastle",
    played: 38,
    won: 18,
    drawn: 6,
    lost: 14,
    goalsFor: 85,
    goalsAgainst: 62,
    points: 60,
    form: ["W", "W", "L", "W", "D"],
  },
  {
    position: 8,
    team: "Manchester United",
    played: 38,
    won: 18,
    drawn: 6,
    lost: 14,
    goalsFor: 57,
    goalsAgainst: 58,
    points: 60,
    form: ["D", "L", "W", "W", "L"],
  },
  {
    position: 9,
    team: "West Ham",
    played: 38,
    won: 14,
    drawn: 10,
    lost: 14,
    goalsFor: 60,
    goalsAgainst: 74,
    points: 52,
    form: ["L", "D", "W", "L", "D"],
  },
  {
    position: 10,
    team: "Crystal Palace",
    played: 38,
    won: 13,
    drawn: 10,
    lost: 15,
    goalsFor: 57,
    goalsAgainst: 58,
    points: 49,
    form: ["D", "W", "L", "D", "W"],
  },
  {
    position: 11,
    team: "Brighton",
    played: 38,
    won: 12,
    drawn: 12,
    lost: 14,
    goalsFor: 55,
    goalsAgainst: 62,
    points: 48,
    form: ["D", "D", "L", "W", "D"],
  },
  {
    position: 12,
    team: "Bournemouth",
    played: 38,
    won: 13,
    drawn: 9,
    lost: 16,
    goalsFor: 54,
    goalsAgainst: 67,
    points: 48,
    form: ["W", "L", "D", "L", "W"],
  },
  {
    position: 13,
    team: "Fulham",
    played: 38,
    won: 13,
    drawn: 8,
    lost: 17,
    goalsFor: 55,
    goalsAgainst: 61,
    points: 47,
    form: ["L", "W", "L", "D", "L"],
  },
  {
    position: 14,
    team: "Wolves",
    played: 38,
    won: 13,
    drawn: 7,
    lost: 18,
    goalsFor: 50,
    goalsAgainst: 65,
    points: 46,
    form: ["L", "L", "W", "L", "D"],
  },
  {
    position: 15,
    team: "Everton",
    played: 38,
    won: 13,
    drawn: 9,
    lost: 16,
    goalsFor: 40,
    goalsAgainst: 51,
    points: 40,
    form: ["D", "L", "D", "W", "L"],
  },
  {
    position: 16,
    team: "Brentford",
    played: 38,
    won: 10,
    drawn: 9,
    lost: 19,
    goalsFor: 56,
    goalsAgainst: 65,
    points: 39,
    form: ["L", "D", "L", "L", "D"],
  },
  {
    position: 17,
    team: "Nottingham Forest",
    played: 38,
    won: 9,
    drawn: 9,
    lost: 20,
    goalsFor: 49,
    goalsAgainst: 67,
    points: 32,
    form: ["L", "D", "L", "L", "W"],
  },
  {
    position: 18,
    team: "Luton Town",
    played: 38,
    won: 6,
    drawn: 8,
    lost: 24,
    goalsFor: 52,
    goalsAgainst: 85,
    points: 26,
    form: ["L", "L", "D", "L", "L"],
  },
  {
    position: 19,
    team: "Burnley",
    played: 38,
    won: 5,
    drawn: 9,
    lost: 24,
    goalsFor: 41,
    goalsAgainst: 78,
    points: 24,
    form: ["L", "D", "L", "L", "L"],
  },
  {
    position: 20,
    team: "Sheffield United",
    played: 38,
    won: 3,
    drawn: 7,
    lost: 28,
    goalsFor: 35,
    goalsAgainst: 104,
    points: 16,
    form: ["L", "L", "L", "D", "L"],
  },
];

export const Primary: Story = {
  args: {
    caption: "2023-24 Premier League Season - Final Standings",
    rows,
  },
};
